version: 2
jobs:
  build_node_image:
    machine:
      enabled: true
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    working_directory: ~/.go_workspace/src/sigs.k8s.io/kind
    steps:
      - run: git clone https://github.com/kubernetes-sigs/kind.git .
      - run: make build
      - run: ./bin/kind build base-image --image aojea/kindbase:latest
      - run: git clone https://github.com/kubernetes/kubernetes.git /tmp/kubernetes
      - run: ./bin/kind build node-image --base-image aojea/kindbase:latest --image aojea/kindnode:latest --type docker --kube-root /tmp/kubernetes --loglevel debug
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl
            chmod +x kubectl
            sudo cp kubectl /usr/local/bin/
      - run:
          name: Create kind cluster
          command: |
            ./bin/kind create cluster --image aojea/kindnode:latest --loglevel debug --wait 1m
            export KUBECONFIG="$(./bin/kind get kubeconfig-path --name="kind")"
            kubectl get nodes -o wide
            kubectl get pods --all-namespaces -o wide
            kubectl get services --all-namespaces -o wide
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push aojea/kindnode:latest

workflows:
  version: 2
  build_images:
    jobs:
      - build_node_image
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_node_image

