version: 2
jobs:
  build_node_image:
    machine:
      enabled: true
      image: ubuntu-1604:201903-01
    working_directory: ~/.go_workspace/src/sigs.k8s.io/kind
    steps:
      - run: git clone https://github.com/kubernetes-sigs/kind.git .
      - run: make build
      - run: git clone https://github.com/kubernetes/kubernetes.git /tmp/kubernetes
      - run: ./bin/kind build node-image --image aojea/kindnode:latest --kube-root /tmp/kubernetes -v=3
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x kubectl
            sudo cp kubectl /usr/local/bin/
      - run:
          name: Create kind cluster
          command: |
            KUBECONFIG="${HOME}/kind-test-config"
            export KUBECONFIG
            ./bin/kind create cluster --image aojea/kindnode:latest -v=3 --wait 1m --retain
            kubectl get nodes -o wide
            kubectl get pods --all-namespaces -o wide
            kubectl get services --all-namespaces -o wide
      - run:
          command: |
            mkdir -p /tmp/kind
            ./bin/kind export logs /tmp/kind
          when: on_fail
      - store_artifacts:
          path: /tmp/kind
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push aojea/kindnode:latest
            export KUBE_VERSION=$(git -C /tmp/kubernetes log -1 --pretty='%h')
            export KIND_VERSION=$(git log -1 --pretty='%h')
            docker tag aojea/kindnode:latest aojea/kindnode:kind${KIND_VERSION}_k8s${KUBE_VERSION}
            docker push aojea/kindnode:kind${KIND_VERSION}_k8s${KUBE_VERSION}

workflows:
  version: 2
  build_images:
    jobs:
      - build_node_image
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_node_image

