name: CNCF

on:
  workflow_dispatch:

jobs:
  release:
    name: CNCF
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        k8s_version: ["v1.23.9", "v1.24.3", "v1.25.0"]
        kind_version: ["v0.15.0"]
    timeout-minutes: 3600
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/${{ matrix.kind_version }}/kind-linux-amd64
          chmod +x ./kind

      - name: Create cluster
        run: |
          cat <<EOF | ./kind create cluster -v7 --wait 1m --retain --image kindest/node:${{ matrix.k8s_version }} --config=-
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
          - role: worker
          - role: worker
          EOF

      - name: Get Cluster status
        run: |
          # wait network is ready
          kubectl wait --for=condition=ready pods --namespace=kube-system -l k8s-app=kube-dns
          kubectl get nodes -o wide
          kubectl get pods -A

      - name: Install suonoboy
        run: |
          curl -L https://github.com/vmware-tanzu/sonobuoy/releases/download/v0.56.10/sonobuoy_0.56.10_linux_amd64.tar.gz -o ./sonobuoy.tar.gz
          tar xvzf ./sonobuoy.tar.gz
          chmod +x ./sonobuoy

      - name: Run conformance
        run: |
          ./sonobuoy run --mode=certified-conformance --wait
          
      - name: Get conformance results
        run: |
          outfile=$(./sonobuoy retrieve)
          mkdir /tmp/results
          tar xzf $outfile -C /tmp/results
          
      - name: Upload conformance results
        uses: actions/upload-artifact@v2
        with:
          name: e2e-results-${{ env.JOB_NAME }}-${{ github.run_id }}
          path: /tmp/results

      - name: Delete cluster
        run: ./kind delete cluster
